blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions for Quoota Vault
    url: https://github.com/gazarrillo/quoota-vault/discussions
    about: Use the discussions to request features or get help with usage/configuration.
  - name: Discourse forum for Quoota Vault
    url: https://quoota-vault.discourse.group/
    about: An alternative to the GitHub Discussions, if this is easier for you.
