services:
  quoota-vault:
    image: ghcr.io/gazarrillo/quoota-vault:testing
    container_name: quoota-vault
    restart: unless-stopped
    volumes:
      - /data/quoota-vault:/data
    env_file:
      - .env
    environment:
      DOMAIN: "https://${DOMAIN}"
      DATABASE_URL: /data/db.sqlite3
      ROCKET_PORT: "80"
      LOG_LEVEL: info
    networks:
      - web

  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    environment:
      DOMAIN: "${DOMAIN}"
    networks:
      - web

volumes:
  caddy_data:
  caddy_config:

networks:
  web:
